name: Check for Updates

on:
  schedule:
    - cron: '0 6 * * *'  # Daily at 6 AM UTC
  workflow_dispatch:

jobs:
  check-updates:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: write

    steps:
    - uses: actions/checkout@v4

    - name: Check WordPress base image updates
      id: wordpress
      run: |
        CURRENT=$(grep "FROM wordpress:" Dockerfile | cut -d: -f2)
        LATEST=$(curl -s "https://registry.hub.docker.com/v2/repositories/library/wordpress/tags/?page_size=100" | jq -r '.results[] | select(.name | test("^[0-9]+\\.[0-9]+\\.[0-9]+-php[0-9]+\\.[0-9]+-fpm-alpine$")) | .name' | sort -V | tail -1)
        echo "current=${CURRENT}" >> $GITHUB_OUTPUT
        echo "latest=${LATEST}" >> $GITHUB_OUTPUT
        if [ "$CURRENT" != "$LATEST" ]; then
          echo "update_needed=true" >> $GITHUB_OUTPUT
        fi

    - name: Check SportsPress plugin updates
      id: sportspress
      run: |
        CURRENT=$(grep "sportspress\." Dockerfile | grep -o "[0-9]\+\.[0-9]\+\.[0-9]\+")
        LATEST=$(curl -s "https://api.wordpress.org/plugins/info/1.0/sportspress.json" | jq -r '.version')
        echo "current=${CURRENT}" >> $GITHUB_OUTPUT
        echo "latest=${LATEST}" >> $GITHUB_OUTPUT
        if [ "$CURRENT" != "$LATEST" ]; then
          echo "update_needed=true" >> $GITHUB_OUTPUT
        fi

    - name: Update Dockerfile
      if: steps.wordpress.outputs.update_needed == 'true' || steps.sportspress.outputs.update_needed == 'true'
      run: |
        if [ "${{ steps.wordpress.outputs.update_needed }}" == "true" ]; then
          sed -i "s/FROM wordpress:.*/FROM wordpress:${{ steps.wordpress.outputs.latest }}/" Dockerfile
        fi
        if [ "${{ steps.sportspress.outputs.update_needed }}" == "true" ]; then
          sed -i "s/sportspress\.[0-9]\+\.[0-9]\+\.[0-9]\+/sportspress.${{ steps.sportspress.outputs.latest }}/g" Dockerfile
        fi

    - name: Create Pull Request
      if: steps.wordpress.outputs.update_needed == 'true' || steps.sportspress.outputs.update_needed == 'true'
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: |
          Update dependencies
          
          - WordPress: ${{ steps.wordpress.outputs.current }} → ${{ steps.wordpress.outputs.latest }}
          - SportsPress: ${{ steps.sportspress.outputs.current }} → ${{ steps.sportspress.outputs.latest }}
        title: 'Update WordPress and SportsPress versions'
        body: |
          Automated update of dependencies:
          
          - WordPress base image: `${{ steps.wordpress.outputs.current }}` → `${{ steps.wordpress.outputs.latest }}`
          - SportsPress plugin: `${{ steps.sportspress.outputs.current }}` → `${{ steps.sportspress.outputs.latest }}`
        branch: update-dependencies